spring.application.name=interview-project

### context-path  ###
server.servlet.context-path=/interview
server.port=8081

### server.servlet.session.cookie.name=apqmnenf ###

### connection pool config ###
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver
spring.datasource.url=jdbc:sqlserver://localhost:1433;database=ShareSpace;trustServerCertificate=true
spring.datasource.username=sa
spring.datasource.password=a192862225

### JPA config ###
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.SQLServerDialect
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

### update for development, validate for test ###
spring.jpa.hibernate.ddl-auto=update
spring.jpa.hibernate.naming.physical-strategy=org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

### upload size limit ###
spring.servlet.multipart.max-file-size=5MB
spring.servlet.multipart.max-request-size=50MB

### JWT key ###
jwt.secret=0123456789012345678901234567890123456789
jwt.expiration=86400000